name: Service Reference
description: Request a new service reference or report an issue with an existing one
title: "[Service]: "
labels: ["service-reference"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - New service
        - Fix existing service
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Context, use case, or what needs fixing
    validations:
      required: false

  - type: checkboxes
    id: self-submit
    attributes:
      label: Contribution
      options:
        - label: I would like to submit this change myself
